.\" @(#) $Id: arpsnmp.8,v 1.5 2000/09/17 20:34:41 leres Exp $ (LBL)
.\"
.\" Copyright (c) 1996, 1997, 1999, 2000
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that: (1) source code distributions
.\" retain the above copyright notice and this paragraph in its entirety, (2)
.\" distributions including binary code include the above copyright notice and
.\" this paragraph in its entirety in the documentation or other materials
.\" provided with the distribution, and (3) all advertising materials mentioning
.\" features or use of this software display the following acknowledgement:
.\" ``This product includes software developed by the University of California,
.\" Lawrence Berkeley Laboratory and its contributors.'' Neither the name of
.\" the University nor the names of its contributors may be used to endorse
.\" or promote products derived from this software without specific prior
.\" written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.TH ARPSNMP 8 "17 September 2000"
.UC 4
.SH NAME
arpsnmp \- keep track of ethernet/ip address pairings
.SH SYNOPSIS
.B arpsnmp
[
.B -d
] [
.B -f
.I datafile
] [
.B -s
.I sendmailprog
] [
.B -t
.I mailto
] [
.I file
[
.I ...
]
.SH DESCRIPTION
.B Arpsnmp
keeps track for ethernet/ip address pairings. It syslogs activity
and reports certain changes via email.
.B Arpsnmp
reads information from a file (usually generated by
.BR snmpwalk (8)).
.LP
.B -d
is used enable debugging. This also inhibits mailing the reports.
Instead, they are sent to
.IR stderr .
.LP
.B -f
is used to set the ethernet/ip address database filename.
The default is
.IR arp.dat .
.LP
Note that an empty
.I arp.dat
file must be created before the first time you run
.BR arpsnmp .
.LP
.B -s
flag is used to specify the path to the sendmail program.
Any program that takes the option -odi and then text from stdin
can be substituted. This is useful for redirecting reports
to log files instead of mail.
.LP
.B -t
option is used to specify the e-mail address to which reports will be
sent.  By default, reports are sent to
.I root
on the local machine.

.LP
.SH "REPORT MESSAGES"
(See the
.BR arpwatch (1)
man page for details on the report messages generated by
.BR arpsnmp (1).)
.SH FILES
.na
.nh
.nf
/usr/operator/arpwatch - default directory
arp.dat - ethernet/ip address database
ethercodes.dat - vendor ethernet block list
.ad
.hy
.fi
.SH "SEE ALSO"
.na
.nh
.BR arpwatch (8),
.BR snmpwalk (8),
.BR arp (8)
.ad
.hy
.SH AUTHORS
Craig Leres of the
Lawrence Berkeley National Laboratory Network Research Group,
University of California, Berkeley, CA.
.LP
The current version is available via anonymous ftp:
.LP
.RS
.I ftp://ftp.ee.lbl.gov/arpwatch.tar.gz
.RE
.SH BUGS
Please send bug reports to arpwatch@ee.lbl.gov.
.LP
Attempts are made to suppress DECnet flip flops but they
aren't always successful.
