.\" @(#) $Id: arpwatch.8,v 1.13 2000/10/08 20:31:25 leres Exp $ (LBL)
.\"
.\" Copyright (c) 1992, 1994, 1996, 1997, 2000
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that: (1) source code distributions
.\" retain the above copyright notice and this paragraph in its entirety, (2)
.\" distributions including binary code include the above copyright notice and
.\" this paragraph in its entirety in the documentation or other materials
.\" provided with the distribution, and (3) all advertising materials mentioning
.\" features or use of this software display the following acknowledgement:
.\" ``This product includes software developed by the University of California,
.\" Lawrence Berkeley Laboratory and its contributors.'' Neither the name of
.\" the University nor the names of its contributors may be used to endorse
.\" or promote products derived from this software without specific prior
.\" written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.TH ARPWATCH 8 "13 SEPTEMBER 2006"
.UC 4
.SH NAME
arpwatch NG \- keep track of ethernet/ip address pairings
.SH SYNOPSIS
.na
.B arpwatch
[
.B -d
] [
.B -f
.I data_file
]
.br
.ti +9
[
.B -i
.I interface
] [
.B -n
.IR net [/ width
]] [
.B -N
] [
.B -r
.I pcap_file
]
.br
.ti +9
[
.B -p
] [
.B -P
.I pcap_filter
]
.br
.ti +9
[
.B -m
.I report_mode
]
.br
.ti +9
[
.B -s
.I sendmail_prog
] [
.B -t
.I mail_to
] [
.B -F
.I mail_from
]
.br
.ti +9
[
.B -u
.I username
]

.ad
.SH DESCRIPTION
.B arpwatch
keeps track for ethernet/ip address pairings. It syslogs activity
and reports certain changes via email.
.B arpwatch
uses
.BR pcap (3)
to listen for arp packets on a local ethernet interface.
.LP
.B -d
is used enable debugging. This also inhibits forking into the
background and emailing the reports. Instead, they are sent to
.IR stdout.
.LP
.B -f
is used to set the ethernet/ip address database filename.
The default is
.IR arp.dat .
.LP
.B -i
is used to override the default interface.
.LP
.B -n
specifies additional local networks. This can be useful to
avoid "bogon" warnings when there is more than one network running
on the same wire. If the optional
.I width
is not specified, the default netmask for the network's class is used.
.LP
.B -N
disables reporting any bogons; see option -n.
.LP
.B -r
is used to specify a savefile
(perhaps created by
.BR tcpdump (1)
or
.BR pcapture (1))
to read from instead
of reading from the network. In this case,
.B arpwatch
does not fork.
.LP
.B -m
selects the output mode (report mode). Currently, 0 means the old mode
(via sendmail), 1 is a simple stdout mode and arpwatch will not fork
into the background. 2 means raw mode, where the fields are separated by 
a ",". Default is 0.
.LP
.B -p
flag disables promiscuous operation.  ARP broadcasts get through hubs without
having the interface in promiscuous mode, while saving considerable resources
that would be wasted on processing gigabytes of non-broadcast traffic.  OTOH,
setting promiscuous mode does not mean getting 100% traffic that would concern
.B arpwatch.
.LP
.B -P
option allows to specify a pcap filter expression for the traffic that
will be watched by arpwatch. Prepended will be
"(arp or rarp) and" to select only the ARP traffic. For expression please
see tcpdump(8). Expressions must be enclosed in quotation marks ("").
.LP
.B Example:
arpwatch -P "src net 10.20.23.0/24"
.LP
.B -s
flag is used to specify the path to the sendmail program.
Any program that takes the option -odi and then text from stdin
can be substituted. This is useful for redirecting reports
to log files instead of mail
.LP
.B -F
option is used to specify From: field of the report message. By
default arpwatch.
.LP
.B -t
option is used to specify the e-mail address to which reports will be
sent.  By default, reports are sent to
.I root
on the local machine.
.LP
.B -u
instructs arpwatch to drop root privileges and change the UID to
.I username
and GID to the primary group of username.
This is recommended for security reasons, but username
has to have write access to the default directory.
.LP

Note that an empty
.I arp.dat
file must be created before the first time you run
.BR arpwatch .
.LP

.SH "REPORT MESSAGES"
Here's a quick list of some of the report messages generated by
.BR arpwatch (1)
(and
.BR arpsnmp (1)):
.TP
.B "new activity"
This ethernet/ip address pair has been used for the first time six
months or more.
.TP
.B "new station"
The ethernet address has not been seen before.
.TP
.B "reused old mac"
The ethernet address has changed from the most recently seen address to
the third (or greater) least recently seen address.
(This is similar to a flip flop.)
.TP
.B "changed mac"
The host switched to a new ethernet address.
.TP
.B "dec flip flop"
The ethernet address has changed from the most recently seen address to
the second most recently seen address.
(If either the old or new ethernet address is a DECnet address and it
is less than 24 hours, the email version of the report is suppressed.)
.TP
.B "bogon"
The source ip address is not local to the local subnet.
.TP
.B "ether broadcast"
The mac ethernet address of the host is a broadcast address.
.TP
.B "ether mismatch"
The source mac ethernet address didn't match the address inside
the arp packet.
.TP
.B "ether too short"
The ARP packet is corrupted and too short.
.TP
.B "suppressed DECnet flip flop"
A "flip flop" report was suppressed because one of the two
addresses was a DECnet address.

.SH FILES
.na
.nh
.nf
/usr/operator/arpwatch - default directory
arp.dat - ethernet/ip address database
ethercodes.dat - vendor ethernet block list
.ad
.hy
.fi

.SH "SEE ALSO"
.na
.nh
.BR arpsnmp(8),
.BR arp(8),
.BR bpf(4),
.BR tcpdump(1),
.BR pcapture(1),
.BR tcpdump(8),
.BR pcap(3)
.ad
.hy

.SH AUTHORS
arpwatch NG was forked by Freek and is based upon the original arpwatch 2.1a13 and works of:
.LP
Craig Leres of the
Lawrence Berkeley National Laboratory Network Research Group,
University of California, Berkeley, CA.
.LP
The old arpwatch is available via anonymous ftp:
.RS
.I ftp://ftp.ee.lbl.gov/arpwatch.tar.gz
.RE

.LP
Numerous Debian vendor patches were merged, thanks to Peter Kelemen
.LP
.LP
arpwatch NG versions are announced at:
.LP
.RS
.I
http://freshmeat.net/projects/arpwatch-ng
.RE

.SH BUGS
Attempts are made to suppress DECnet flip flops but they
aren't always successful.
.LP
Most error messages are posted using syslog.
